name: Update submodules

on:
  workflow_dispatch:    # allow manual trigger
  schedule:
    - cron: '0 3 * * *' # optional: run daily

permissions:
  contents: write       # 👈 this line gives GITHUB_TOKEN push permission

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git diff --cached --quiet || git commit -m "Auto-update submodules"
          git push