name: Update submodules
on:
  schedule:
    - cron: '0 3 * * *'  # every day at 03:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git diff --cached --quiet || git commit -m "Auto-update submodules"
          git push
